"""Seed TaintedPort app with all known vulnerabilities on first startup."""

TAINTEDPORT_APP = {
    "name": "TaintedPort",
    "version": "1.0",
    "description": "Intentionally vulnerable wine store application for security testing. "
                   "Built with PHP backend + Next.js frontend + SQLite database.",
    "url": "https://taintedport.com",
}

TAINTEDPORT_TECH_STACK = ["PHP", "Next.js", "SQLite", "Nginx", "Docker"]

TAINTEDPORT_VULNS = [
    {
        "vuln_id": "TP-001",
        "title": "SQL Injection - Login Email",
        "severity": "high",
        "vuln_type": "SQLi",
        "http_method": "POST",
        "url": "/auth/login",
        "parameter": "email",
        "description": "The email value is directly concatenated into a SQL query without parameterized statements. An attacker can inject SQL via the email field to bypass authentication or extract data.",
        "code_location": "backend/api/models/User.php -> authenticateDirect() line 41",
        "poc": "email = ' OR 1=1 --",
        "remediation": "Use parameterized queries with bound parameters.",
    },
    {
        "vuln_id": "TP-002",
        "title": "SQL Injection - Wine Detail (ID in URL)",
        "severity": "high",
        "vuln_type": "SQLi",
        "http_method": "GET",
        "url": "/wines/:id",
        "parameter": "id",
        "description": "The wine ID is directly concatenated into a SQL query. The route accepts non-numeric values, allowing SQL injection.",
        "code_location": "backend/api/models/Wine.php -> getByIdDirect() line 89",
        "poc": "GET /wines/0 UNION SELECT 1,email,password_hash,name,5,6,7,8,totp_secret,is_admin,11,12,13,14,15 FROM users--",
        "remediation": "Use a parameterized query with the id bound as an integer.",
    },
    {
        "vuln_id": "TP-003",
        "title": "SQL Injection - Wine Search",
        "severity": "high",
        "vuln_type": "SQLi",
        "http_method": "GET",
        "url": "/wines",
        "parameter": "search",
        "description": "The search term is directly concatenated into the SQL LIKE clause without parameterized statements.",
        "code_location": "backend/api/models/Wine.php -> getAll() line 18",
        "poc": "search=' UNION SELECT 1,email,password_hash,name,5,6,7,8 FROM users--",
        "remediation": "Use a parameterized query with bound wildcards.",
    },
    {
        "vuln_id": "TP-004",
        "title": "SQL Injection - Wine Reviews",
        "severity": "high",
        "vuln_type": "SQLi",
        "http_method": "GET",
        "url": "/wines/:id/reviews",
        "parameter": "id",
        "description": "The wine ID is directly concatenated into the SQL query when fetching reviews.",
        "code_location": "backend/api/models/Review.php -> getByWineId() line 16",
        "poc": "GET /wines/0 UNION SELECT 1,email,password_hash,name,5,6 FROM users--/reviews",
        "remediation": "Use a parameterized query.",
    },
    {
        "vuln_id": "TP-005",
        "title": "Blind SQL Injection - Order Status Filter",
        "severity": "high",
        "vuln_type": "SQLi",
        "http_method": "GET",
        "url": "/orders",
        "parameter": "status",
        "description": "The order listing endpoint accepts a status filter that is concatenated directly into the SQL query. This enables time-based blind SQL injection.",
        "code_location": "backend/api/models/Order.php -> getByUserFiltered() line 85",
        "poc": "status=pending' AND 1=CASE WHEN (SELECT length(password_hash) FROM users WHERE id=1)>50 THEN RANDOMBLOB(200000000) ELSE 1 END--",
        "remediation": "Use a parameterized query with bound parameters.",
    },
    {
        "vuln_id": "TP-006",
        "title": "Reflected XSS - Login Email",
        "severity": "medium",
        "vuln_type": "XSS",
        "http_method": "POST",
        "url": "/auth/login",
        "parameter": "email",
        "description": "On failed login, the error message includes the raw email address without HTML encoding. The frontend renders it using dangerouslySetInnerHTML.",
        "code_location": "backend/api/controllers/AuthController.php line 72; frontend/app/login/page.js line 90",
        "poc": "email = <script>alert(1)</script>",
        "remediation": "Server-side: HTML-encode the email with htmlspecialchars(). Client-side: use text rendering instead of dangerouslySetInnerHTML.",
    },
    {
        "vuln_id": "TP-007",
        "title": "Reflected XSS - Wine Search",
        "severity": "medium",
        "vuln_type": "XSS",
        "http_method": "GET",
        "url": "/wines",
        "parameter": "search",
        "description": "The search query is returned in the API response as-is. The frontend renders this using dangerouslySetInnerHTML, enabling XSS.",
        "code_location": "backend/api/controllers/WineController.php line 46; frontend/app/wines/WinesCatalog.js line 83",
        "poc": "search=<img src=x onerror=alert(1)>",
        "remediation": "Server-side: HTML-encode the search query. Client-side: use text rendering.",
    },
    {
        "vuln_id": "TP-008",
        "title": "Stored XSS - User Name (Profile)",
        "severity": "medium",
        "vuln_type": "XSS",
        "http_method": "PUT",
        "url": "/auth/profile",
        "parameter": "name",
        "description": "The user's name is stored without sanitization and rendered in the navigation bar using dangerouslySetInnerHTML. Executes on every page load.",
        "code_location": "frontend/components/Navbar.js line 26",
        "poc": "name = <img src=x onerror=alert(document.cookie)>",
        "remediation": "Use JSX text interpolation instead of dangerouslySetInnerHTML.",
    },
    {
        "vuln_id": "TP-009",
        "title": "Stored XSS - Shipping Name (Checkout)",
        "severity": "medium",
        "vuln_type": "XSS",
        "http_method": "POST",
        "url": "/orders",
        "parameter": "shipping_address.name",
        "description": "The shipping name entered during checkout is stored and rendered on the order detail page using dangerouslySetInnerHTML.",
        "code_location": "frontend/app/orders/[id]/page.js line 95",
        "poc": "name = <script>alert('XSS')</script>",
        "remediation": "Use JSX text interpolation instead of dangerouslySetInnerHTML.",
    },
    {
        "vuln_id": "TP-010",
        "title": "Stored XSS - Wine Review Comment",
        "severity": "medium",
        "vuln_type": "XSS",
        "http_method": "POST",
        "url": "/wines/:id/reviews",
        "parameter": "comment",
        "description": "The review comment is stored without sanitization and rendered using dangerouslySetInnerHTML. Any visitor sees the XSS payload.",
        "code_location": "frontend/app/wines/[id]/page.js line 395",
        "poc": "comment = <img src=x onerror=alert(document.cookie)>",
        "remediation": "Use JSX text interpolation or DOMPurify.",
    },
    {
        "vuln_id": "TP-011",
        "title": "JWT 'none' Algorithm Accepted",
        "severity": "high",
        "vuln_type": "Broken Authentication",
        "http_method": "GET",
        "url": "/*",
        "parameter": "Authorization",
        "description": "The JWT decoder accepts alg=none and skips signature verification entirely. An attacker can forge tokens with arbitrary payloads.",
        "code_location": "backend/api/config/jwt.php lines 34-40",
        "poc": 'Header={"alg":"none","typ":"JWT"}, Payload={"user_id":1,"email":"admin@example.com","exp":9999999999}',
        "remediation": "Reject any token where alg is not the expected algorithm (HS256).",
    },
    {
        "vuln_id": "TP-012",
        "title": "JWT Signature Not Verified",
        "severity": "high",
        "vuln_type": "Broken Authentication",
        "http_method": "GET",
        "url": "/*",
        "parameter": "Authorization",
        "description": "For HS256 tokens, when the signature doesn't match, the code only logs a warning but still accepts the token. Attackers can modify any JWT payload without the secret key.",
        "code_location": "backend/api/config/jwt.php lines 46-48",
        "poc": "Modify the user_id in any JWT payload, re-encode without valid signature.",
        "remediation": "Return null (reject the token) when the signature does not match.",
    },
    {
        "vuln_id": "TP-013",
        "title": "Directory Listing",
        "severity": "medium",
        "vuln_type": "Information Disclosure",
        "http_method": "GET",
        "url": "/files/",
        "parameter": None,
        "description": "Nginx is configured with autoindex enabled on /files/, exposing all PHP source code, the SQLite database file, and configuration files including the JWT secret.",
        "code_location": "docker/nginx.conf lines 47 and 79",
        "poc": "Browse to /files/ to see directory listing.",
        "remediation": "Remove the autoindex directive or set it to off.",
    },
    {
        "vuln_id": "TP-014",
        "title": "Path Traversal - Wine Export",
        "severity": "high",
        "vuln_type": "Path Traversal",
        "http_method": "GET",
        "url": "/wines/export/:filename",
        "parameter": "filename",
        "description": "The wine export endpoint serves files from an exports directory but does not sanitize the filename parameter. Allows reading arbitrary server files.",
        "code_location": "backend/api/controllers/WineController.php line 79",
        "poc": "GET /wines/export/../../api/config/jwt.php (leaks JWT secret)\nGET /wines/export/../../database.db (leaks entire database)",
        "remediation": "Use basename() to strip directory traversal sequences, or validate realpath stays within the base directory.",
    },
    {
        "vuln_id": "TP-015",
        "title": "Open Redirect on Login",
        "severity": "medium",
        "vuln_type": "Open Redirect",
        "http_method": "POST",
        "url": "/auth/login",
        "parameter": "redirect",
        "description": "The login endpoint accepts a redirect parameter. After successful login, the frontend navigates to the URL without validation.",
        "code_location": "backend/api/controllers/AuthController.php line 109; frontend/app/login/page.js",
        "poc": '{"email":"joe@example.com","password":"password123","redirect":"https://evil.com"}',
        "remediation": "Validate the redirect URL is a relative path or same-origin.",
    },
    {
        "vuln_id": "TP-016",
        "title": "Missing Security Headers",
        "severity": "low",
        "vuln_type": "Security Misconfiguration",
        "http_method": "GET",
        "url": "/*",
        "parameter": None,
        "description": "The application does not set critical security headers: Strict-Transport-Security (HSTS), X-Content-Type-Options: nosniff, X-Frame-Options.",
        "code_location": "docker/nginx.conf; backend/api/index.php lines 4-11",
        "poc": "Check response headers on any endpoint.",
        "remediation": "Add HSTS, X-Content-Type-Options: nosniff, X-Frame-Options: DENY headers.",
    },
    {
        "vuln_id": "TP-017",
        "title": "BOLA (IDOR) on Order Details",
        "severity": "high",
        "vuln_type": "IDOR",
        "http_method": "GET",
        "url": "/orders/:id",
        "parameter": "id",
        "description": "The order detail endpoint does not verify that the authenticated user owns the order. Any authenticated user can view any order by guessing or enumerating order IDs.",
        "code_location": "backend/api/models/Order.php line 104",
        "poc": "GET /orders/1 as any authenticated user (even non-owner).",
        "remediation": "Add user ownership check: WHERE o.id = :id AND o.user_id = :user_id.",
    },
    {
        "vuln_id": "TP-018",
        "title": "BOLA / Mass Assignment on Profile Update",
        "severity": "high",
        "vuln_type": "IDOR",
        "http_method": "PUT",
        "url": "/auth/profile",
        "parameter": "user_id",
        "description": "The profile update endpoint accepts an optional user_id parameter. If provided, it updates that user's name instead of the authenticated user's.",
        "code_location": "backend/api/controllers/AuthController.php line 150",
        "poc": '{"user_id": 3, "name": "hacked"} as any authenticated user.',
        "remediation": "Always use the authenticated user's ID; ignore client-supplied user_id.",
    },
    {
        "vuln_id": "TP-019",
        "title": "Price Manipulation on Cart",
        "severity": "high",
        "vuln_type": "Business Logic",
        "http_method": "POST",
        "url": "/cart/add",
        "parameter": "price",
        "description": "The cart add endpoint accepts an optional price field which updates the wine's price in the database. An attacker can set any wine's price to 0.01.",
        "code_location": "backend/api/controllers/CartController.php line 32; backend/api/models/Cart.php lines 44-48",
        "poc": '{"wine_id": 1, "quantity": 1, "price": 0.01}',
        "remediation": "Remove the $customPrice parameter entirely. Always use the database price.",
    },
    {
        "vuln_id": "TP-020",
        "title": "Broken Access Control on 2FA Disable",
        "severity": "high",
        "vuln_type": "Broken Access Control",
        "http_method": "POST",
        "url": "/auth/2fa/disable",
        "parameter": "user_id",
        "description": "The 2FA disable endpoint accepts an optional user_id parameter. An attacker can disable any user's 2FA by providing their user_id.",
        "code_location": "backend/api/controllers/AuthController.php line 328",
        "poc": '{"user_id": 3, "password": "mypassword"} to disable admin 2FA.',
        "remediation": "Always use the authenticated user's ID.",
    },
    {
        "vuln_id": "TP-021",
        "title": "Discount Code Bypass",
        "severity": "high",
        "vuln_type": "Business Logic",
        "http_method": "POST",
        "url": "/orders",
        "parameter": "discount_percent",
        "description": "The checkout accepts discount_code and discount_percent fields. Any non-empty discount_code is accepted as valid, and discount_percent is applied directly without validation.",
        "code_location": "backend/api/controllers/OrderController.php lines 32-36",
        "poc": '{"discount_code": "anything", "discount_percent": 100} for a free order.',
        "remediation": "Validate discount codes against a server-side database. Never accept the percentage from the client.",
    },
    {
        "vuln_id": "TP-022",
        "title": "Privilege Escalation via Mass Assignment on Registration",
        "severity": "critical",
        "vuln_type": "Privilege Escalation",
        "http_method": "POST",
        "url": "/auth/register",
        "parameter": "is_admin",
        "description": "The registration endpoint accepts an optional is_admin field. If is_admin=1 is sent, the new account is created with admin privileges.",
        "code_location": "backend/api/controllers/AuthController.php line 38",
        "poc": '{"name":"attacker","email":"evil@test.com","password":"pass123","is_admin":1}',
        "remediation": "Hardcode isAdmin to 0 for all registrations.",
    },
    {
        "vuln_id": "TP-023",
        "title": "Privilege Escalation via JWT Claim Forgery",
        "severity": "critical",
        "vuln_type": "Privilege Escalation",
        "http_method": "GET",
        "url": "/admin/*",
        "parameter": "Authorization",
        "description": "The admin authorization check reads is_admin from the JWT payload instead of the database. Combined with JWT vulns (#11, #12), an attacker can forge a token with is_admin=true.",
        "code_location": "backend/api/controllers/AdminController.php line 18",
        "poc": "Login as any user, decode JWT, set is_admin=true, re-encode with alg=none.",
        "remediation": "Look up admin status from the database, not the JWT payload.",
    },
    {
        "vuln_id": "TP-024",
        "title": "BOPLA - Excessive Data Exposure on Order Details",
        "severity": "high",
        "vuln_type": "Data Exposure",
        "http_method": "GET",
        "url": "/orders/:id",
        "parameter": "id",
        "description": "The order detail endpoint JOINs with users table and returns password_hash, totp_secret, and is_admin flag in the response.",
        "code_location": "backend/api/models/Order.php lines 99-101",
        "poc": "GET /orders/1 — response includes owner_password_hash, owner_totp_secret.",
        "remediation": "Only SELECT fields needed for display (name, email). Never expose password_hash or totp_secret.",
    },
    {
        "vuln_id": "TP-025",
        "title": "BFLA - Broken Function Level Authorization on Order Status",
        "severity": "high",
        "vuln_type": "Broken Access Control",
        "http_method": "PUT",
        "url": "/orders/:id/status",
        "parameter": "is_admin",
        "description": "The order status update endpoint checks if is_admin=true was passed in the request body instead of verifying the user's actual role. Any user can change any order's status.",
        "code_location": "backend/api/controllers/OrderController.php lines 78-81",
        "poc": '{"status": "cancelled", "is_admin": true} as any authenticated user.',
        "remediation": "Check admin status from the authenticated user (JWT or database), not from the request body.",
    },
    {
        "vuln_id": "TP-027",
        "title": "SSRF via Wine Import URL",
        "severity": "high",
        "vuln_type": "SSRF",
        "http_method": "POST",
        "url": "/wines/import-url",
        "parameter": "url",
        "description": "The wine import endpoint fetches content from a user-supplied URL using file_get_contents(), which supports file://, http://, and other PHP stream wrappers. An attacker can read arbitrary local files. This enables a chain: (1) read file:///var/www/backend/api/config/jwt.php, (2) extract the JWT secret, (3) forge a properly HS256-signed admin token.",
        "code_location": "backend/api/controllers/WineController.php",
        "poc": '{"url": "file:///var/www/backend/api/config/jwt.php"}',
        "remediation": "Validate the URL scheme (allow only https://), block private/internal IPs, and use curl with CURLOPT_PROTOCOLS instead of file_get_contents().",
    },
    {
        "vuln_id": "TP-028",
        "title": "SQLi -> TOTP Secret Extraction -> 2FA Bypass -> Account Takeover",
        "severity": "critical",
        "vuln_type": "SQLi",
        "http_method": "GET",
        "url": "/wines",
        "parameter": "search",
        "description": "Vulnerability chain combining SQL injection with TOTP secret theft to fully bypass 2FA and take over any account. Steps: (1) Use SQLi to extract email, password_hash, and totp_secret for all users, (2) crack password offline, (3) compute valid TOTP codes from stolen secret, (4) login as victim with valid 2FA.",
        "code_location": "backend/api/models/Wine.php -> getAll(); backend/api/controllers/AuthController.php -> login()",
        "poc": "search=' UNION SELECT 1,email,password_hash,name,5,6,totp_secret,totp_enabled FROM users--",
        "remediation": "Fix the underlying SQL injection vulnerabilities. Store TOTP secrets encrypted at rest.",
    },
    {
        "vuln_id": "TP-029",
        "title": "Reflected XSS - Contact Form Preview (Server-Side)",
        "severity": "medium",
        "vuln_type": "XSS",
        "http_method": "POST",
        "url": "/contact/preview",
        "parameter": "name",
        "description": "The contact form preview endpoint receives form data and renders an HTML page with form values embedded directly without escaping. Unlike other XSS vulns in this app (DOM-based via dangerouslySetInnerHTML), this is a traditional server-side reflected XSS. All four form fields (name, email, subject, message) are vulnerable.",
        "code_location": "backend/api/controllers/ContactController.php",
        "poc": "name=<script>alert(document.cookie)</script>",
        "remediation": "HTML-encode all user input with htmlspecialchars() before embedding in the page.",
    },
]


async def seed_taintedport(db, admin_user_id: int):
    """Insert TaintedPort app and all known vulnerabilities if not already present."""
    cursor = await db.execute(
        "SELECT id FROM apps WHERE name = ? AND version = ?",
        (TAINTEDPORT_APP["name"], TAINTEDPORT_APP["version"]),
    )
    existing = await cursor.fetchone()
    if existing:
        return

    cursor = await db.execute(
        "INSERT INTO apps (name, version, description, url, created_by) VALUES (?, ?, ?, ?, ?)",
        (
            TAINTEDPORT_APP["name"],
            TAINTEDPORT_APP["version"],
            TAINTEDPORT_APP["description"],
            TAINTEDPORT_APP["url"],
            admin_user_id,
        ),
    )
    app_id = cursor.lastrowid

    for tech in TAINTEDPORT_TECH_STACK:
        await db.execute(
            "INSERT OR IGNORE INTO app_technologies (app_id, name) VALUES (?, ?)",
            (app_id, tech),
        )

    for v in TAINTEDPORT_VULNS:
        await db.execute(
            """INSERT INTO vulnerabilities
               (app_id, vuln_id, title, severity, vuln_type, http_method, url, parameter,
                description, code_location, poc, remediation, created_by)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                app_id,
                v["vuln_id"],
                v["title"],
                v["severity"],
                v["vuln_type"],
                v.get("http_method"),
                v.get("url"),
                v.get("parameter"),
                v.get("description"),
                v.get("code_location"),
                v.get("poc"),
                v.get("remediation"),
                admin_user_id,
            ),
        )

    await db.commit()
